### ISSUE TITLE
Exception in main thread after new XML Parser

### ISSUE THREAD

**Issue by jketcham** [TeamTyro/color-maze-game#2]
Exception in thread "main" java.lang.NullPointerException
    at sql.XMLParser.<init>(XMLParser.java:14)
    at MazeGame.packUp(MazeGame.java:402)
    at MazeGame.begin(MazeGame.java:90)
    at MazeGame.main(MazeGame.java:56)

This exception is being shown now when trying to run the maze game as a result to the recently changed XML Parser system.

**Comment by jketcham** [comment]
37a3c023b64d3c890bac373668193b119485f2bb Fixes the issue. Closing
![20120607035837_auto](https://f.cloud.github.com/assets/1548556/212433/ce2e9f62-82fe-11e2-891e-0aa3cbaf22e4.gif)
